import { z } from 'zod';

export const destinoSchema = z.object({
  name: z.string().min(3, 'Nome deve ter pelo menos 3 caracteres'),
  slug: z.string().min(3, 'Slug deve ter pelo menos 3 caracteres'),
  description: z.string().optional(),
  content: z.string().optional(),
  bannerTitle: z.string().optional(),
  imageUrl: z.string().url('URL inválida').optional().or(z.literal('')),
  country: z.string().min(2, 'País é obrigatório'),
  continent: z.enum(['América do Norte', 'América do Sul', 'Europa', 'Ásia', 'África', 'Oceania']),
  highlights: z.string().optional(),
  status: z.enum(['draft', 'published']),
  // Campos das principais cidades
  cityEnabled: z.boolean().default(false),
  cityTitle: z.string().optional(),
  cityDescription: z.string().optional(),
  city1Title: z.string().optional(),
  city1Description: z.string().optional(),
  city1Image: z.string().url('URL inválida').optional().or(z.literal('')),
  city2Title: z.string().optional(),
  city2Description: z.string().optional(),
  city2Image: z.string().url('URL inválida').optional().or(z.literal('')),
  city3Title: z.string().optional(),
  city3Description: z.string().optional(),
  city3Image: z.string().url('URL inválida').optional().or(z.literal('')),
  city4Title: z.string().optional(),
  city4Description: z.string().optional(),
  city4Image: z.string().url('URL inválida').optional().or(z.literal('')),
  // Campos dos diferenciais
  diferenciaisEnabled: z.boolean().default(false),
  diferenciaisTitle: z.string().optional(),
  diferenciaisDescription: z.string().optional(),
  diferencial1Title: z.string().optional(),
  diferencial1Description: z.string().optional(),
  diferencial1Image: z.string().url('URL inválida').optional().or(z.literal('')),
  diferencial2Title: z.string().optional(),
  diferencial2Description: z.string().optional(),
  diferencial2Image: z.string().url('URL inválida').optional().or(z.literal('')),
  diferencial3Title: z.string().optional(),
  diferencial3Description: z.string().optional(),
  diferencial3Image: z.string().url('URL inválida').optional().or(z.literal('')),
  diferencial4Title: z.string().optional(),
  diferencial4Description: z.string().optional(),
  diferencial4Image: z.string().url('URL inválida').optional().or(z.literal('')),
  // Campos dos benefícios
  beneficiosEnabled: z.boolean().default(false),
  beneficiosTitle: z.string().optional(),
  beneficiosDescription: z.string().optional(),
  beneficio1Title: z.string().optional(),
  beneficio1Description: z.string().optional(),
  beneficio1Icon: z.string().optional(),
  beneficio2Title: z.string().optional(),
  beneficio2Description: z.string().optional(),
  beneficio2Icon: z.string().optional(),
  beneficio3Title: z.string().optional(),
  beneficio3Description: z.string().optional(),
  beneficio3Icon: z.string().optional(),
  beneficio4Title: z.string().optional(),
  beneficio4Description: z.string().optional(),
  beneficio4Icon: z.string().optional(),
  beneficio5Title: z.string().optional(),
  beneficio5Description: z.string().optional(),
  beneficio5Icon: z.string().optional(),
  beneficio6Title: z.string().optional(),
  beneficio6Description: z.string().optional(),
  beneficio6Icon: z.string().optional(),
  // Campos dos requisitos especiais
  requisitosEnabled: z.boolean().default(false),
  requisitosTitle: z.string().optional(),
  requisitosDescription: z.string().optional(),
  requisitosBreadcrumb: z.string().optional(),
  requisitosButtonText: z.string().optional(),
  requisitosButtonUrl: z.string().optional(),
  requisito1Title: z.string().optional(),
  requisito1Description: z.string().optional(),
  requisito1Icon: z.string().optional(),
  requisito2Title: z.string().optional(),
  requisito2Description: z.string().optional(),
  requisito2Icon: z.string().optional(),
  requisito3Title: z.string().optional(),
  requisito3Description: z.string().optional(),
  requisito3Icon: z.string().optional(),
  requisito4Title: z.string().optional(),
  requisito4Description: z.string().optional(),
  requisito4Icon: z.string().optional(),
  requisito5Title: z.string().optional(),
  requisito5Description: z.string().optional(),
  requisito5Icon: z.string().optional(),
  requisito6Title: z.string().optional(),
  requisito6Description: z.string().optional(),
  requisito6Icon: z.string().optional(),
  requisito7Title: z.string().optional(),
  requisito7Description: z.string().optional(),
  requisito7Icon: z.string().optional(),
  requisito8Title: z.string().optional(),
  requisito8Description: z.string().optional(),
  requisito8Icon: z.string().optional(),
  // Campos do CTA
  ctaEnabled: z.boolean().default(false),
  ctaTitle: z.string().max(100, 'Título do CTA deve ter no máximo 100 caracteres').optional(),
  ctaDescription: z.string().max(300, 'Descrição do CTA deve ter no máximo 300 caracteres').optional(),
  ctaButtonText: z.string().max(50, 'Texto do botão deve ter no máximo 50 caracteres').optional(),
  ctaButtonUrl: z.string().optional()
});

export type DestinoFormData = z.infer<typeof destinoSchema>;

