import { z } from 'zod';

export const vistoSchema = z.object({
  title: z.string().min(3, 'Título deve ter pelo menos 3 caracteres'),
  slug: z.string().min(3, 'Slug deve ter pelo menos 3 caracteres'),
  description: z.string().min(10, 'Descrição deve ter pelo menos 10 caracteres'),
  imageUrl: z.string().url('URL inválida').optional().or(z.literal('')),
  country: z.string().min(2, 'País é obrigatório'),
  vistoType: z.enum(['turismo', 'trabalho', 'estudo', 'investidor']),
  status: z.enum(['draft', 'published']),
  // Novos campos para o padrão blog/FAQ
  excerpt: z.string().max(500, 'Resumo deve ter no máximo 500 caracteres').optional(),
  content: z.string().optional(),
  bannerTitle: z.string().max(100, 'Título do banner deve ter no máximo 100 caracteres').optional(),
  // Campos do banner dinâmico
  bannerEnabled: z.boolean().default(false),
  bannerDescription: z.string().max(300, 'Descrição do banner deve ter no máximo 300 caracteres').optional(),
  bannerButtonText: z.string().max(50, 'Texto do botão deve ter no máximo 50 caracteres').optional(),
  bannerButtonUrl: z.string().url('URL do botão inválida').optional().or(z.literal('')),
  // Campos do CTA dinâmico
  ctaTitle: z.string().max(100, 'Título do CTA deve ter no máximo 100 caracteres').optional(),
  ctaDescription: z.string().max(300, 'Descrição do CTA deve ter no máximo 300 caracteres').optional(),
  ctaButtonText: z.string().max(50, 'Texto do botão deve ter no máximo 50 caracteres').optional(),
  ctaButtonUrl: z.string().optional(),
  videoUrl: z.string().url('URL do vídeo inválida').optional().or(z.literal('')),
  // Campos das principais cidades
  cityEnabled: z.boolean().default(false),
  cityTitle: z.string().max(100, 'Título da seção deve ter no máximo 100 caracteres').optional(),
  cityDescription: z.string().max(200, 'Descrição da seção deve ter no máximo 200 caracteres').optional(),
  city1Title: z.string().max(100, 'Título da cidade 1 deve ter no máximo 100 caracteres').optional(),
  city1Description: z.string().max(300, 'Descrição da cidade 1 deve ter no máximo 300 caracteres').optional(),
  city1Image: z.string().url('URL inválida').optional().or(z.literal('')),
  city2Title: z.string().max(100, 'Título da cidade 2 deve ter no máximo 100 caracteres').optional(),
  city2Description: z.string().max(300, 'Descrição da cidade 2 deve ter no máximo 300 caracteres').optional(),
  city2Image: z.string().url('URL inválida').optional().or(z.literal('')),
  city3Title: z.string().max(100, 'Título da cidade 3 deve ter no máximo 100 caracteres').optional(),
  city3Description: z.string().max(300, 'Descrição da cidade 3 deve ter no máximo 300 caracteres').optional(),
  city3Image: z.string().url('URL inválida').optional().or(z.literal('')),
  city4Title: z.string().max(100, 'Título da cidade 4 deve ter no máximo 100 caracteres').optional(),
  city4Description: z.string().max(300, 'Descrição da cidade 4 deve ter no máximo 300 caracteres').optional(),
  city4Image: z.string().url('URL inválida').optional().or(z.literal('')),
  // Campos do FAQ
  faqEnabled: z.boolean().default(false),
  faqTitle: z.string().max(100, 'Título da seção FAQ deve ter no máximo 100 caracteres').optional(),
  faqDescription: z.string().max(200, 'Descrição da seção FAQ deve ter no máximo 200 caracteres').optional(),
  faq1Question: z.string().max(200, 'Pergunta 1 deve ter no máximo 200 caracteres').optional(),
  faq1Answer: z.string().max(1000, 'Resposta 1 deve ter no máximo 1000 caracteres').optional(),
  faq2Question: z.string().max(200, 'Pergunta 2 deve ter no máximo 200 caracteres').optional(),
  faq2Answer: z.string().max(1000, 'Resposta 2 deve ter no máximo 1000 caracteres').optional(),
  faq3Question: z.string().max(200, 'Pergunta 3 deve ter no máximo 200 caracteres').optional(),
  faq3Answer: z.string().max(1000, 'Resposta 3 deve ter no máximo 1000 caracteres').optional(),
  faq4Question: z.string().max(200, 'Pergunta 4 deve ter no máximo 200 caracteres').optional(),
  faq4Answer: z.string().max(1000, 'Resposta 4 deve ter no máximo 1000 caracteres').optional(),
  faq5Question: z.string().max(200, 'Pergunta 5 deve ter no máximo 200 caracteres').optional(),
  faq5Answer: z.string().max(1000, 'Resposta 5 deve ter no máximo 1000 caracteres').optional(),
  faq6Question: z.string().max(200, 'Pergunta 6 deve ter no máximo 200 caracteres').optional(),
  faq6Answer: z.string().max(1000, 'Resposta 6 deve ter no máximo 1000 caracteres').optional(),
  // Campos dos diferenciais
  diferenciaisEnabled: z.boolean().default(false),
  diferenciaisTitle: z.string().max(100, 'Título da seção deve ter no máximo 100 caracteres').optional(),
  diferenciaisDescription: z.string().max(200, 'Descrição da seção deve ter no máximo 200 caracteres').optional(),
  diferencial1Title: z.string().max(100, 'Título do diferencial 1 deve ter no máximo 100 caracteres').optional(),
  diferencial1Description: z.string().max(300, 'Descrição do diferencial 1 deve ter no máximo 300 caracteres').optional(),
  diferencial1Image: z.string().url('URL inválida').optional().or(z.literal('')),
  diferencial2Title: z.string().max(100, 'Título do diferencial 2 deve ter no máximo 100 caracteres').optional(),
  diferencial2Description: z.string().max(300, 'Descrição do diferencial 2 deve ter no máximo 300 caracteres').optional(),
  diferencial2Image: z.string().url('URL inválida').optional().or(z.literal('')),
  diferencial3Title: z.string().max(100, 'Título do diferencial 3 deve ter no máximo 100 caracteres').optional(),
  diferencial3Description: z.string().max(300, 'Descrição do diferencial 3 deve ter no máximo 300 caracteres').optional(),
  diferencial3Image: z.string().url('URL inválida').optional().or(z.literal('')),
  diferencial4Title: z.string().max(100, 'Título do diferencial 4 deve ter no máximo 100 caracteres').optional(),
  diferencial4Description: z.string().max(300, 'Descrição do diferencial 4 deve ter no máximo 300 caracteres').optional(),
  diferencial4Image: z.string().url('URL inválida').optional().or(z.literal('')),
  // Campos dos benefícios
  beneficiosEnabled: z.boolean().default(false),
  beneficio1Title: z.string().max(100, 'Título do benefício 1 deve ter no máximo 100 caracteres').optional(),
  beneficio1Description: z.string().max(300, 'Descrição do benefício 1 deve ter no máximo 300 caracteres').optional(),
  beneficio1Icon: z.string().optional(),
  beneficio2Title: z.string().max(100, 'Título do benefício 2 deve ter no máximo 100 caracteres').optional(),
  beneficio2Description: z.string().max(300, 'Descrição do benefício 2 deve ter no máximo 300 caracteres').optional(),
  beneficio2Icon: z.string().optional(),
  beneficio3Title: z.string().max(100, 'Título do benefício 3 deve ter no máximo 100 caracteres').optional(),
  beneficio3Description: z.string().max(300, 'Descrição do benefício 3 deve ter no máximo 300 caracteres').optional(),
  beneficio3Icon: z.string().optional(),
  // Campos dos requisitos especiais
  requisitosEnabled: z.boolean().default(false),
  requisitosBreadcrumb: z.string().max(50, 'Breadcrumb deve ter no máximo 50 caracteres').optional(),
  requisitosTitle: z.string().max(100, 'Título da seção deve ter no máximo 100 caracteres').optional(),
  requisitosDescription: z.string().max(200, 'Descrição da seção deve ter no máximo 200 caracteres').optional(),
  requisitosButtonText: z.string().max(50, 'Texto do botão deve ter no máximo 50 caracteres').optional(),
  requisitosButtonUrl: z.string().optional(),
  requisito1Title: z.string().max(100, 'Título do requisito 1 deve ter no máximo 100 caracteres').optional(),
  requisito1Description: z.string().max(300, 'Descrição do requisito 1 deve ter no máximo 300 caracteres').optional(),
  requisito1Icon: z.string().optional(),
  requisito2Title: z.string().max(100, 'Título do requisito 2 deve ter no máximo 100 caracteres').optional(),
  requisito2Description: z.string().max(300, 'Descrição do requisito 2 deve ter no máximo 300 caracteres').optional(),
  requisito2Icon: z.string().optional(),
  requisito3Title: z.string().max(100, 'Título do requisito 3 deve ter no máximo 100 caracteres').optional(),
  requisito3Description: z.string().max(300, 'Descrição do requisito 3 deve ter no máximo 300 caracteres').optional(),
  requisito3Icon: z.string().optional(),
  requisito4Title: z.string().max(100, 'Título do requisito 4 deve ter no máximo 100 caracteres').optional(),
  requisito4Description: z.string().max(300, 'Descrição do requisito 4 deve ter no máximo 300 caracteres').optional(),
  requisito4Icon: z.string().optional(),
  requisito5Title: z.string().max(100, 'Título do requisito 5 deve ter no máximo 100 caracteres').optional(),
  requisito5Description: z.string().max(300, 'Descrição do requisito 5 deve ter no máximo 300 caracteres').optional(),
  requisito5Icon: z.string().optional(),
  requisito6Title: z.string().max(100, 'Título do requisito 6 deve ter no máximo 100 caracteres').optional(),
  requisito6Description: z.string().max(300, 'Descrição do requisito 6 deve ter no máximo 300 caracteres').optional(),
  requisito6Icon: z.string().optional(),
  requisito7Title: z.string().max(100, 'Título do requisito 7 deve ter no máximo 100 caracteres').optional(),
  requisito7Description: z.string().max(300, 'Descrição do requisito 7 deve ter no máximo 300 caracteres').optional(),
  requisito7Icon: z.string().optional(),
  requisito8Title: z.string().max(100, 'Título do requisito 8 deve ter no máximo 100 caracteres').optional(),
  requisito8Description: z.string().max(300, 'Descrição do requisito 8 deve ter no máximo 300 caracteres').optional(),
  requisito8Icon: z.string().optional(),
  authorId: z.string().optional(),
  metaTitle: z.string().optional(),
  metaDescription: z.string().optional(),
  metaKeywords: z.string().optional(),
  ogTitle: z.string().optional(),
  ogDescription: z.string().optional(),
  ogImage: z.string().optional(),
  twitterTitle: z.string().optional(),
  twitterDescription: z.string().optional(),
  twitterImage: z.string().optional()
});

export type VistoFormData = z.infer<typeof vistoSchema>;

